# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: appdev-staging-environment
#   namespace: argocd
#   finalizers:
#     - resources-finalizer.argocd.argoproj.io
# spec:
#   project: staging-env
#   source:
#     path: helm
#     repoURL: https://github.com/niranjan-mookambika/appdev.git
#     targetRevision: master
#     helm:
#       version: v3
#       values: |
#         local: true
#   destination:
#     namespace: staging-env
#     server: https://kubernetes.default.svc
#   syncPolicy:
#     automated:
#       selfHeal: true
#       prune: true
